- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Creating the Container
      docker_container:
        name: edgecut-container
        image: edgecut:latest
        ports:
          - "80:80"
        state: started
        restart: true
